version: 0.2

env:
  variables:
    IMAGE_REPO_NAME: "cohesion"            # Change to your ECR repo name
    IMAGE_TAG: "latest"

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
      - REGION=$(aws configure get region)
      - REPOSITORY_URI=${ACCOUNT_ID}.dkr.ecr.${REGION}.amazonaws.com/${IMAGE_REPO_NAME}
      - aws ecr get-login-password --region $REGION | docker login --username AWS --password-stdin $REPOSITORY_URI

  build:
    commands:
      - echo Building Docker image...
      - docker build -t $IMAGE_REPO_NAME .
      - docker tag $IMAGE_REPO_NAME:latest $REPOSITORY_URI:$IMAGE_TAG

  post_build:
    commands:
      - echo Pushing image to ECR...
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo $REPOSITORY_URI:$IMAGE_TAG > imageDetail.txt
      - mkdir -p deploy
      - cp appspec.yaml deploy/
      - cp -r scripts deploy/
      - cp imageDetail.txt deploy/
      - cd deploy
      - zip -r ../deploy.zip .
      - cd ..

artifacts:
  files:
    - deploy.zip

