version: '3.9'

services:
  myapp:
    build:
      context: .
      dockerfile: Dockerfile
    image: myapp:latest
    container_name: myapp
    ports:
      - "8005:80"  # Map host port 8080 to container port 80 (Nginx)
    restart: unless-stopped
    environment:
      NODE_ENV: production
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

